name: Auto Label Issues
on:
  issues:
    types: [opened, reopened]
jobs:
  check-external:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.is-member.outputs.result }}
    steps:
    - name: Get deps
      run: |
        sudo apt-get update && sudo apt-get install -y jq
    - name: Get org members
      id: is-member
      env:
        GH_ORG: supabase
        GH_USER: ${{ github.event.issue.user.login }}
        GH_TOKEN: ${{ secrets.SB_ORG_MEMBERSHIP_PAT }}
      run: |
        gh api /orgs/supabase/members/$GH_USER
    - if: failure()
      name: is-external
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ github.event.issue.user.login }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.issue.number }}
        LABELS: external-issue
      run: |
        echo "User is not a member of Supabase org"
        echo "result=false" >> "$GITHUB_OUTPUT"
        gh issue edit $NUMBER --add-label $LABELS
    - if: success()
      name: is-internal
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ github.event.issue.user.login }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.issue.number }}
        LABELS: internal-issue
      run: |
        echo "User is a member of Supabase org"
        echo "result=true" >> "$GITHUB_OUTPUT"
        gh issue edit $NUMBER --add-label $LABELS
  triage-new:
    runs-on: ubuntu-latest
    steps:
      - name: Label triage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: to-triage
        run: |
          echo "applying triage label"
          gh issue edit $NUMBER --add-label $LABELS
